server:
  port: 8112

spring:
  application:
    name: gateway-service  # Gateway 的服务名
  cloud:
    consul:
      host: consul  # Consul 地址
      port: 8500       # Consul 端口
      discovery:
        service-name:  gateway-service # Consul 服务的名称
        instance-id: gateway-service-${random.value}
        health-check-interval: 10s     # 健康检查间隔
    gateway:
      httpclient:
        connect-timeout: 5000  # 设置连接超时为 5 秒
        response-timeout: 30000  # 设置响应超时为 30 秒
      routes:
        - id: recommend-service-route
          uri: lb://recommend-service
          predicates:
            - Path=/recommend/**
        - id: test-service-route
          uri: lb://test-service
          predicates:
            - Path=/test/**
      discovery:
        locator:
          enabled: true  # 启用服务自动发现和路由
logging:
  level:
    root: INFO              # 设置默认日志级别
  file:
    path: ./logs            # 日志文件的存储路径
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # 控制台输出格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 文件输出格式
