apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa  # HPA 的名称
  namespace: default  # HPA 所属的命名空间
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommend  # 要扩展的 Deployment 名称
  minReplicas: 2  # 最小副本数
  maxReplicas: 10  # 最大副本数
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # 当 CPU 使用率超过 50% 时扩展
